### ISSUE TITLE
A map error will appear after killing two dragons.

### ISSUE THREAD

**Issue by FTLIKON** [MarioCrane/LeaueLobby#1]
![ERROR](https://user-images.githubusercontent.com/51710525/85193052-b1549c80-b2f7-11ea-95df-418b64f9e7b5.png)

**Comment by MarioCrane** [comment]
Sorry this is a game bug, i cannot fix it.

**Comment by MarioCrane** [comment]
我是国人，说中文就行

**Comment by FTLIKON** [comment]
> 我是国人，说中文就行

是游戏问题吗？但我创建普通模式时并不会遇到这种问题。。您创建5v5训练时会发生这种问题吗（在击杀第二条龙之后）

**Comment by MarioCrane** [comment]
从来没有遇到过，这个是跟龙的属性有关的，龙不同就会导致地面不同，你这个就是地面的资源丢失了

**Comment by FTLIKON** [comment]
> 从来没有遇到过，这个是跟龙的属性有关的，龙不同就会导致地面不同，你这个就是地面的资源丢失了

好的，感谢回复

**Comment by MarioCrane** [comment]
这个问题之前就有国人反馈过，但官方一直没有进行修复，估计要等等了
