### ISSUE TITLE
I can't create the 5v5 training mode....

### ISSUE THREAD

**Issue by Einsturing** [MarioCrane/LeaueLobby#2]
When I create the 5v5 training mode, it says:

{"errorCode":"RPC_ERROR","httpStatus":435,"implementationDetails":{},"message":"Couldn't change lobby: Error creating lobby: Error response for POST /lol-login/v1/session/invoke: LCDS invoke to gameService.createPracticeGame failed: Server.Processing, com.riotgames.platform.game.GameModeNotSupportedException : Custom game disabled or mismatched"}

The game's version is v10.19. What should I do?

**Comment by MarioCrane** [comment]
应该是服务器的原因，最近服务器一直在维护

**Comment by Einsturing** [comment]
感谢！
