### ISSUE TITLE
无法使用JSON创建房间

### ISSUE THREAD

**Issue by XHXIAIEIN** [MarioCrane/LeaueLobby#3]
创建5V5训练模式后，将返回的JSON数据重新粘贴到上方，再点击根据JSON创建，也会提示
```
{"errorCode":"RPC_ERROR","httpStatus":500,"implementationDetails":{},"message":"INVALID_LOBBY"}
```

所以按目前的功能，更希望能通过JSON自定义创建5V5训练模式。
比如，我可以先创建房间，选好机器人队友，工具可以读取房间的数据，这样下次就可以直接从这个数据创建房间，不用每次都一个个选了。

如果作者有精力继续开发的话，后面还可以直接在工具中选好队友，然后一键创建？

---
看到工具有个递增选项，是用来一个个试queueID 的吗？

虽然看到官方的API这列表：
https://developer.riotgames.com/docs/lol#general_queue-ids

但是试了一下，输入queueID能进的，其实能直接在客户端点开...
比如有匹配、排位、云顶...现在极限闪击也可以用queueID打开
但是其他特殊模式都不能进入(比如无限火力、克隆大作战...)

**Comment by MarioCrane** [comment]
返回的json是房间的信息，不能用于创建房间，5V5的json我分享在b站了。
queueID创建不了是因为不同服的服务器配置不同，正式服比较严谨。在软件刚做出来的时候，国服的体验服是可以创建血月杀那些特殊模式的，PBE也可以创建云顶教学模式和1V0（后被拳头官方加入云顶的可选模式）。
添加AI调用的是另一套API，只用创建房间的API没法加AI。交流群里面有群友做的一个加强版，可以添加任意难度的AI，有兴趣的话可以去试试，或者晚些我传上来。

**Comment by MarioCrane** [comment]
[LeagueLobbyWinForm版.zip](https://github.com/MarioCrane/LeaueLobby/files/5754509/LeagueLobbyWinForm.zip)

**Comment by XHXIAIEIN** [comment]
> [LeagueLobbyWinForm版.zip](https://github.com/MarioCrane/LeaueLobby/files/5754509/LeagueLobbyWinForm.zip)

感谢!
