### ISSUE TITLE
Is it possible to change MapID to 12 and play on Howling Abyss (极地)

### ISSUE THREAD

**Issue by henryzshao** [MarioCrane/LeaueLobby#6]
Practice tool 5v5 on Howling Abyss

Or bots in Howling Abyss

可以用这个加人机到自定义房间的极地地图吗？
如果可以的话，可以把极地地图变成5v5训练营吗？

**Comment by MarioCrane** [comment]
极地加人机不清楚。不能把极地变成训练营，极地和训练营本就是两个模式

**Comment by henryzshao** [comment]
说以是不可以吧？伤心，不过谢谢。
