### ISSUE TITLE
11月18日更新之后，国服无法使用了

### ISSUE THREAD

**Issue by zzpro** [MarioCrane/LeaueLobby#8]
实测美测服PBE还是可以用
但是国服无法使用，提示无法获取到召唤师信息
请问是什么问题呢
![tes1](https://user-images.githubusercontent.com/2764508/142366110-36f0c865-9e5e-4ae8-9dc4-fdbab782a77d.png)
？

**Comment by MarioCrane** [comment]
这次更新把lockfile去掉了，现在客户端不会生成lockfile导致获取不到端口和token，需要获取LeagueClientUx.exe的运行参数取出端口和token


------------------ 原始邮件 ------------------
发件人: Zhengzheng ***@***.***&gt;
发送时间: 2021年11月18日 14:47
收件人: MarioCrane/LeagueLobby ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: 回复：[MarioCrane/LeagueLobby] 11月18日更新之后，国服无法使用了 (Issue #8)





 
实测美测服PBE还是可以用
 但是国服无法使用，提示无法获取到召唤师信息
 请问是什么问题呢
 
 ？

**Comment by zzpro** [comment]
好的，获取LeagueClientUx.exe的运行参数的方法已经研究出来了吗

**Comment by MarioCrane** [comment]
用win api或者wmic都可以


------------------ 原始邮件 ------------------
发件人: Zhengzheng ***@***.***&gt;
发送时间: 2021年11月18日 14:54
收件人: MarioCrane/LeagueLobby ***@***.***&gt;
抄送: Mario ***@***.***&gt;, Comment ***@***.***&gt;
主题: 回复：[MarioCrane/LeagueLobby] 11月18日更新之后，国服无法使用了 (Issue #8)





 
好的，获取LeagueClientUx.exe的运行参数的方法已经研究出来了吗

**Comment by zzpro** [comment]
好的，麻烦大佬也更新一下程序，因为有不少玩家都有在国服开5V5训练模式的需求。

**Comment by MarioCrane** [comment]
好的，晚上回去我更新下


------------------ 原始邮件 ------------------
发件人: Zhengzheng ***@***.***&gt;
发送时间: 2021年11月18日 15:55
收件人: MarioCrane/LeagueLobby ***@***.***&gt;
抄送: Mario ***@***.***&gt;, Comment ***@***.***&gt;
主题: 回复：[MarioCrane/LeagueLobby] 11月18日更新之后，国服无法使用了 (Issue #8)





 
好的，麻烦大佬也更新一下程序，因为有不少玩家都有在国服开5V5训练模式的需求。

**Comment by MarioCrane** [comment]
更新好了，链接：https://pan.baidu.com/s/1XM5Pmlyoq0EANYJYA7YzBg
提取码：u726 

获取port和token的代码：
```cpp
auto midStr = [=] (const QString &string, const QString &left, const QString &right) {
    auto start = string.indexOf(left, 0);
    auto end = string.indexOf(right, start);
    auto leftSize = left.size();
    return string.mid(start + leftSize, end - start - leftSize);
 };

QProcess process;
process.start("wmic process where caption='LeagueClientUx.exe' get commandline");
process.waitForFinished(-1);
QString result = QString::fromLocal8Bit(process.readAllStandardOutput());

token = midStr(result, "--remoting-auth-token=", "\"");
port = midStr(result, "--app-port=", "\"");
