### ISSUE TITLE
LeagueLobby portable English version

### ISSUE THREAD

**Issue by leemjnc** [MarioCrane/LeaueLobby#9]
你能用英文制作便携版吗？ 
因为中文不熟练 可能的话
thanks.

**Comment by MarioCrane** [comment]
Sure, https://github.com/MarioCrane/LeagueLobby/releases/download/English/LeagueLobbyPortable.exe

**Comment by leemjnc** [comment]
谢谢。

**Comment by leemjnc** [comment]
"Forced match"意味着什么呢

**Comment by MarioCrane** [comment]
> "Forced match"意味着什么呢

Invalid function

**Comment by leemjnc** [comment]
thanks
